# Generated by Django 4.2 on 2023-04-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="roles",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("SUPERUSER", "SUPERUSER"),
                    ("READONLY", "READONLY"),
                ],
                default="READONLY",
                max_length=255,
            ),
        ),
    ]
