# Generated by Django 4.2 on 2023-04-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_users_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
