# Generated by Django 4.2 on 2023-04-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_store_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="create_at",
        ),
        migrations.AddField(
            model_name="products",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="date_of_birth",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="roles",
            field=models.CharField(
                choices=[
                    ("READONLY", "READONLY"),
                    ("SUPERUSER", "SUPERUSER"),
                    ("ADMIN", "ADMIN"),
                ],
                default="READONLY",
                max_length=255,
            ),
        ),
    ]
