# Generated by Django 4.2 on 2023-04-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_users_create_at_products_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="drinks",
            field=models.JSONField(max_length=255),
        ),
        migrations.AlterField(
            model_name="products",
            name="foods",
            field=models.JSONField(max_length=255),
        ),
    ]
