# Generated by Django 4.2 on 2023-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_products_drinks_alter_products_foods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="drinks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="foods",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
