# Generated by Django 4.2 on 2023-04-25 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_products_drinks_alter_products_foods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="drinks",
        ),
        migrations.RemoveField(
            model_name="products",
            name="foods",
        ),
    ]
