# Generated by Django 4.2 on 2023-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_products_drinks_products_foods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
