# Generated by Django 4.2 on 2023-04-28 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_products_created_at_alter_store_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Storename",
                to="users.store",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Users.first_name+",
                to="users.users",
            ),
        ),
    ]
