# Generated by Django 4.2 on 2023-04-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_products_store_alter_store_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Users.first_name+last_name+",
                to="users.users",
            ),
        ),
    ]
