# Generated by Django 4.2 on 2023-04-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_store_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Store.name+",
                to="users.store",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="User.first_name+",
                to="users.users",
            ),
        ),
    ]
