# Generated by Django 4.2 on 2023-05-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_store_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
                to_field="email",
            ),
        ),
    ]
