# Generated by Django 4.2 on 2023-09-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="requests",
            name="store_origin",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
