# Generated by Django 4.2 on 2023-09-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_requests_store_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests",
            name="customer_destination",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="store_origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
