# Generated by Django 4.2 on 2023-09-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_requests_customer_destination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.store",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
